pipeline {
    agent { label 'AGENT-1'}
    environment { 
        PROJECT = 'EXPENSE'
        COMPONENT = 'BACKEND'

    }
    options { 
        disableConcurrentBuilds()
        timeout(time: 32, unit: 'MINUTES')
        ansiColor('xterm')
    }
    /* parameters {
        
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Pick something')

        
    } */
         
    stages{
        stage('init') {  
            steps {
                script{
                  withAWS(region: 'us-east-1', credentials: 'aws-creds') {   
                    sh """
                     cd 00-vpc
                     terraform init -reconfigure
                     terraform plan
                    """ 
                  }
                }
                
            }
        }
        stage('apply') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
            }    
            steps {
                script{
                  withAWS(region: 'us-east-1', credentials: 'aws-creds') {   
                    sh """
                     cd 00-vpc
                     terraform apply -auto-approve
                     
                    """ 
                  }
                }
                
            }

        }
        /* stage('trigger sg'){
            when{
                expression { params.ACTION = 'apply'}
            }
            steps {
                build job: "10-sg", parameters: [string(name: 'ACTION', value: 'apply')], propagate: false
            }
        } */
        stage('destroy') {  
            steps {
                script{
                  withAWS(region: 'us-east-1', credentials: 'aws-creds') {   
                    sh """
                     cd 00-vpc
                     terraform destroy -auto-approve
                    """ 
                  }
                }
                
            }
        } 
    }    
    
        /* stage('Trigger Downstream') {
            when {
                expression = { params.ACTION = 'apply' }
            }
            steps {
                build job: '10-sg' parameters: [string(name: 'ACTION', value: 'apply')],
                propagate = true 

            }  
        } */
     
    
             
    post { 
        always { 
            echo 'I will always say Hello again!'
            deleteDir()
        }
        failure { 
            echo 'I will run when pipeline is failed'
        }
        success { 
            echo 'I will run when pipeline is success'
        }
    }
}